"""
Curated CEFR vocabulary seed (A1–C2) with brief English meanings.
Public-domain common-word selection — enough to power level estimation and
suggestions. Extend freely; the importer is idempotent (keyed on word+level).
"""

CEFR_WORDS = [
    # ── A1 ──
    ("house", "A1", "a building where people live"),
    ("water", "A1", "the clear liquid we drink"),
    ("friend", "A1", "a person you like and know well"),
    ("happy", "A1", "feeling good and pleased"),
    ("eat", "A1", "to put food in your mouth"),
    ("big", "A1", "large in size"),
    ("school", "A1", "a place where children learn"),
    ("family", "A1", "parents and their children"),
    ("good", "A1", "of high quality; pleasant"),
    ("day", "A1", "24 hours; the time it is light"),
    ("book", "A1", "pages with text bound together"),
    ("city", "A1", "a large town"),
    ("work", "A1", "a job; to do a job"),
    ("food", "A1", "things people eat"),
    ("small", "A1", "little in size"),

    # ── A2 ──
    ("travel", "A2", "to go from one place to another"),
    ("weather", "A2", "the state of the sky and air"),
    ("healthy", "A2", "in good physical condition"),
    ("busy", "A2", "having a lot to do"),
    ("remember", "A2", "to keep in your mind"),
    ("decide", "A2", "to choose after thinking"),
    ("important", "A2", "having great value or effect"),
    ("ticket", "A2", "a paper that lets you enter or travel"),
    ("future", "A2", "the time that will come"),
    ("exercise", "A2", "physical activity for health"),
    ("improve", "A2", "to make or become better"),
    ("market", "A2", "a place to buy and sell"),
    ("comfortable", "A2", "giving a relaxed feeling"),
    ("explain", "A2", "to make something clear"),
    ("popular", "A2", "liked by many people"),

    # ── B1 ──
    ("achieve", "B1", "to succeed in doing something"),
    ("advantage", "B1", "a helpful or useful quality"),
    ("behaviour", "B1", "the way someone acts"),
    ("confident", "B1", "sure about your abilities"),
    ("environment", "B1", "the natural world around us"),
    ("experience", "B1", "knowledge from doing things"),
    ("opportunity", "B1", "a chance to do something"),
    ("recognise", "B1", "to know something you have seen before"),
    ("responsible", "B1", "having a duty to deal with something"),
    ("suggest", "B1", "to put forward an idea"),
    ("benefit", "B1", "a helpful or good effect"),
    ("attitude", "B1", "a way of thinking or feeling"),
    ("encourage", "B1", "to give support or hope"),
    ("familiar", "B1", "well known or easily recognised"),
    ("typical", "B1", "showing the usual qualities"),

    # ── B2 ──
    ("ambiguous", "B2", "having more than one meaning"),
    ("anticipate", "B2", "to expect or predict"),
    ("consequence", "B2", "a result of an action"),
    ("contribute", "B2", "to give in order to help"),
    ("diverse", "B2", "showing a lot of variety"),
    ("efficient", "B2", "working well without waste"),
    ("emphasis", "B2", "special importance given to something"),
    ("inevitable", "B2", "certain to happen"),
    ("perceive", "B2", "to become aware of"),
    ("reluctant", "B2", "unwilling and hesitant"),
    ("significant", "B2", "large enough to matter"),
    ("subtle", "B2", "not obvious; delicate"),
    ("sufficient", "B2", "enough for a purpose"),
    ("tendency", "B2", "an inclination to act a certain way"),
    ("versatile", "B2", "able to do many things"),

    # ── C1 ──
    ("ambivalent", "C1", "having mixed feelings"),
    ("coherent", "C1", "logical and consistent"),
    ("compelling", "C1", "powerfully convincing"),
    ("contemplate", "C1", "to think about deeply"),
    ("discrepancy", "C1", "a lack of agreement"),
    ("eloquent", "C1", "fluent and persuasive in speech"),
    ("intricate", "C1", "very detailed and complex"),
    ("meticulous", "C1", "very careful about detail"),
    ("nuance", "C1", "a subtle difference"),
    ("plausible", "C1", "seeming reasonable or probable"),
    ("profound", "C1", "very great or deep"),
    ("resilient", "C1", "able to recover quickly"),
    ("scrutiny", "C1", "close and careful examination"),
    ("undermine", "C1", "to weaken gradually"),
    ("viable", "C1", "able to work successfully"),

    # ── C2 ──
    ("astute", "C2", "clever and quick to understand"),
    ("cogent", "C2", "clear, logical and convincing"),
    ("ephemeral", "C2", "lasting a very short time"),
    ("esoteric", "C2", "understood by only a few"),
    ("idiosyncratic", "C2", "peculiar to an individual"),
    ("juxtapose", "C2", "to place close together for contrast"),
    ("nebulous", "C2", "vague and unclear"),
    ("paradigm", "C2", "a typical model or pattern"),
    ("pernicious", "C2", "having a harmful effect"),
    ("quintessential", "C2", "the most perfect example"),
    ("ubiquitous", "C2", "present everywhere"),
    ("vicarious", "C2", "felt through another's experience"),
    ("zealous", "C2", "showing great energy for a cause"),
    ("ostensible", "C2", "stated but perhaps not true"),
    ("inadvertent", "C2", "not done on purpose"),
]
